# Generated by Django 5.2 on 2025-04-30 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hostel_images/')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='petcareapp.district')),
            ],
        ),
    ]
